### ISSUE TITLE
Фильтр "—" выдает лишние статьи

### ISSUE THREAD

**Issue by bzaar** [gramdict/gramdict#146]
http://gramdict.ru/search/*?additional=%E2%80%94

Например, такие статьи не должны выдаваться:

![image](https://user-images.githubusercontent.com/4028922/85175892-6a6f9400-b270-11ea-9296-b3835d2018cf.png)

А вот эти выдаются правильно:

![image](https://user-images.githubusercontent.com/4028922/85176091-e8cc3600-b270-11ea-8fc6-114e9d168295.png)

Т.е. должен учитываться только минус - [часть индекса](http://gramdict.ru/declension/symbols#minus-nouns), а не тире.

Оценка 1 час.

**Comment by GoToNightmare** [comment]
Сделать тут или в апи?
Можно ответ изменить, как в https://github.com/morpher-ru/gramdict/issues/138

**Comment by bzaar** [comment]
Однозначно в АПИ. На клиенте можно поменять текст статьи, но не количество статей. Фильтровать статьи - дело АПИ, а не клиента. Оценка 2 часа.

**Comment by damartyan** [comment]
Ошибка не исправлена...

**Comment by bzaar** [comment]
This is fixed now.
