### ISSUE TITLE
Wrong stress mark in датчанин

### ISSUE THREAD

**Issue by Fifis** [gramdict/gramdict#203]
There is a typo in [gramdictru/Pages/preface1.cshtml](https://github.com/gramdict/gramdict/blob/f67b1b4b2c63de3fa62ccd10b5019b241f1d7eca/gramdictru/Pages/preface1.cshtml#L316), line 316:
```
<code>да&#769;тчанин, ассири&#769;ец, гунн, млекопита&#769;ющее, земново&#769;дное</code>
```

It should be `датча&#769;нин`, as it is in the dictionary.

**Comment by bzaar** [comment]
[Исправлено](https://gramdict.ru/preface1#non-pluralia-tantum:~:text=да­т­ча́нин). Спасибо, что написали!
